---
- name: Add MongoDB repository key
  apt_key:
    url: https://pgp.mongodb.com/server-7.0.asc
    keyring: /usr/share/keyrings/mongodb-server-7.0.gpg
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
    state: present
    filename: mongodb-org-7.0
    update_cache: yes

- name: Install MongoDB packages
  apt:
    name:
      - mongodb-org=7.0.14
      - mongodb-org-server=7.0.14
      - mongodb-org-shell=7.0.14
      - mongodb-org-mongos=7.0.14
      - mongodb-org-tools=7.0.14
    state: present

- name: Ensure MongoDB group exists
  group:
    name: "{{ mongodb_group | default('mongod') }}"
    state: present

- name: Ensure MongoDB user exists
  user:
    name: "{{ mongodb_user | default('mongod') }}"
    group: "{{ mongodb_group | default('mongod') }}"
    state: present

- name: Disable default MongoDB service
  systemd:
    name: mongod
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Install numactl
  apt:
    name: numactl
    state: present

- name: Disable AppArmor for MongoDB
  command: aa-disable /usr/bin/mongod
  ignore_errors: yes
