# Stage 1: Build the React app with Vite
FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve the build with Nginx
FROM nginx:alpine

# Copy built frontend to Nginx directory
COPY --from=build /app/dist /usr/share/nginx/html

# set correct permissions 
RUN chown -R nginx:nginx /usr/share/nginx/html

# Drop to nginx user 
USER nginx

# Expose port 80 for serving app
EXPOSE 80

# Healthcheck 
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost || exit 1

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
