apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: quay.io/bilelrifi/job-portal-backend
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/mydb
