apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/bilelrifi/job-portal-frontend:v4
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://backend-service:3000
