apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-portal.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.mongo.secretName }}
          {{- if .Values.mongo.persistence.enabled }}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistent-storage
          {{- end }}
      {{- if .Values.mongo.persistence.enabled }}
      volumes:
        - name: mongo-persistent-storage 
          persistentVolumeClaim:
            claimName: gamma-db-pvc
      {{- end }}
