apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-portal.fullname" . }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          {{- if .Values.backend.secretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.backend.secretName }}
          {{- end }}

