apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-portal.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
          envFrom:
            - secretRef:
                name: {{ .Values.mongo.secretName }}
          volumeMounts:
            - name: mongo-configdb
              mountPath: /data/configdb
            - name: mongo-datadb
              mountPath: /data/db
              {{- if .Values.mongo.persistence.enabled }}
            - mountPath: /data/db
              name: mongo-persistent-storage
              {{- end }}
      volumes:
        - name: mongo-configdb
          emptyDir: {}
        - name: mongo-datadb
          emptyDir: {}
          {{- if .Values.mongo.persistence.enabled }}
        - name: mongo-persistent-storage 
          persistentVolumeClaim:
            claimName: gamma-db-pvc
          {{- end }}
