apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-portal.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: {{ .Values.mongo.containerPort }}
          {{- if .Values.mongo.secretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.mongo.secretName }}
          {{- end }}

          
