apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-portal.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
          - name: VITE_API_BASE_URL 
            value: "https://job-portal-dev-myapp-backend-gamma.apps.ocp.smartek.ae"
          - name: CLOUD_NAME
            value: "dq8ariioz" 
          #  - configMapRef:
          #      name: {{ .Values.frontend.configMapName }}
          #resources: {{- toYaml .Values.frontend.resources | nindent 12 }}
