apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gamma-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storage }}
  volumeName: gamma-db-pv 
  storageClassName: ""    
