apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "job-portal.fullname" . }}-backend
  labels:
    app: {{ .Values.global.appName }}-backend
spec:
  to:
    kind: Service
    name: {{ include "job-portal.fullname" . }}-backend
  port:
    targetPort: http
