apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secretName }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo.secret.MONGO_INITDB_ROOT_USERNAME | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo.secret.MONGO_INITDB_ROOT_PASSWORD | quote }}
