apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
type: Opaque
stringData:
  API_KEY: {{ .Values.backend.env.API_KEY | quote }}
  API_SECRET: {{ .Values.backend.env.API_SECRET | quote }}
  CLOUD_NAME: {{ .Values.backend.env.CLOUD_NAME | quote }}
  MONGO_URL: {{ tpl .Values.backend.env.MONGO_URL . | quote }}
  SECRET_KEY: {{ .Values.backend.env.SECRET_KEY | quote }}
  CORS_ORIGIN: {{ .Values.backend.env.CORS_ORIGIN | quote }}
