apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-portal.fullname" . }}-backend
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.appName }}-backend
  ports:
    - port: 3000
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
      name: http
