apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-portal.fullname" . }}-mongo
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.appName }}-mongo
  ports:
    - port: 27017
      targetPort: {{ .Values.mongo.containerPort }}
      protocol: TCP
      name: mongo
