apiVersion: v1
kind: Service
metadata:
  name: {{ include "job-portal.fullname" . }}-frontend
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.global.appName }}-frontend
  ports:
    - port: 8080
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
      name: http
