frontend:
  enabled: true 
  config:
    VITE_API_BASE_URL: "https://job-portal-backend-gamma.apps.ocp.smartek.ae/api"

backend:
  env:
    API_KEY: "858319527567711"
    API_SECRET: "zvNVBmcA32j7XWdPaFJOeit-5ow"
    CLOUD_NAME: "dq8ariioz"
    MONGO_URL: "mongodb://admin:admin@{{ .Release.Name }}-myapp-mongo:27017/job_portal?authSource=admin"
    SECRET_KEY: "HarHarMahadev"
    CORS_ORIGIN: "https://job-portal-frontend-gamma.apps.ocp.smartek.ae"

mongo:
  secret:
    MONGO_INITDB_ROOT_USERNAME: "admin"
    MONGO_INITDB_ROOT_PASSWORD: "admin"
    MONGO_INITDB_DATABASE: "job_portal"