global:
  appName: job-portal

frontend:
  enabled: true 
  image:
    repository: quay.io/bilelrifi/job-portal-frontend
    tag: v6
  containerPort: 8080
  configMapName: frontend-config
  config:
    CLOUD_NAME: dq8ariioz
    VITE_API_BASE_URL: http://localhost:3000/api
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

backend:
  image:
    repository: quay.io/bilelrifi/job-portal-backend
    tag: v6
  containerPort: 3000
  secretName: backend-secrets
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

mongo:
  image:
    repository: quay.io/bilelrifi/job-portal-mongo
    tag: v6
  containerPort: 27017
  secretName: mongo-secrets
  storage: 1Gi
