FROM mongo:7.0

ENV MONGO_INITDB_DATABASE=job_portal
ENV MONGO_INITDB_ROOT_USERNAME=admin
ENV MONGO_INITDB_ROOT_PASSWORD=admin

EXPOSE 27017

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
  CMD mongo --eval "db.adminCommand('ping')" || exit 1
